version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iamjuan_frontend_dev
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8081:80
    environment:
      - WATCHPACK_POLLING=true
    command: npm run dev
