name: Deploy

on:
  push:
    branches: [dev]
env:
  BUILD_DIR: ./out
  DOMAIN: iamjuan.dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: npm ci
      - run: npm run build
      - name: Add CNAME
        run: echo ${{env.DOMAIN}} >> ${{env.BUILD_DIR}}/CNAME
      - name: Add .nojekyll
        run: touch ${{env.BUILD_DIR}}/.nojekyll
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{env.BUILD_DIR}}
          publish_branch: master
          enable_jekyll: false
